### PR TITLE
Read description CAREFULLY!

### PR DESCRIPTION
**Pull request by evaxrut**
Added support for local development database

You will need to make your own local postgres database, easy with 
```
docker run --name verklegt2 -e POSTGRES_PASSWORD=unsafepw-d -p 5432:5432 postgres
```
Then copy `.env.example` to `.env`, and fill in the fields (should be easy enough). DO NOT check .env into github.

To create dummy data first run 
```
 python manage.py makemigrations                                                                                                                                                                                             
 python manage.py migrate
 python scripts/createFakeData.py
```

Should be able to see the fake data on admin page

### CODE REVIEW

**Review by hv4r3rv4ll1 — APPROVED** [review]
Strange and maybe redundant soon but sure why not

**Review by ViggoRu21 — APPROVED** [review]
ég stend alltaf með sjálfstæði

**Review by MFernirjons — APPROVED** [review]
LGTM : >

**Comment by evaxrut** [comment]
> Strange and maybe redundant soon but sure why not

what do you mean?

**Pull request merged**
